digraph mesh {
v3 -> v1 [color=blue]
v1 -> v2 [color=blue]
v2 -> v3 [color=blue]
v1 -> v3 [color=green]
v1 -> v4
v4 -> v2 [color=blue]
v2 -> v1
v4 -> v1 [color=green]
v4 -> v5
v5 -> v2 [color=blue]
v2 -> v4
v5 -> v4 [color=green]
v5 -> v6
v6 -> v2 [color=blue]
v2 -> v5
v6 -> v5 [color=green]
v6 -> v7
v7 -> v2 [color=blue]
v2 -> v6
v7 -> v6 [color=green]
v7 -> v3
v3 -> v2
v2 -> v7
v3 -> v7 [color=green]
}
